openapi: 3.0.0
info:
  title: "Grace API"
  description: "A REST API for Users to store and utilize database information."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Church:
      type: "object"
      required:
        - churchId
        - churchName
        - churchPhone
        - churchLocation
      properties:
        churchId:
          type: integer
          example: 1
        churchName:
          type: string
          example: Grace in the Desert
        churchPhone:
          type: string
          example: 123-456-7890
        churchLocation:
          type: string
          example: https://goo.gl/maps/kgbHCRVMULdtATzF7

    Members:
      type: "object"
      required:
        - memberId
        - churchId
        - firstName
        - lastName
        - email
        - password
        - mobile
        - emailList
        - prayerList
        - position
      properties:
        memberId:
          type: integer
        churchId:
          type: integer
        firstName:
          type: String
        lastName:
          type: String
        email:
          type: email
        password:
          type: password
        mobile:
          type: int
        emailList:
          type: true
        prayerList:
          type: true
        position:
          type: String

  parameters:
    fname:
      name: "fname"
      description: "User's first name"
      in: path
      required: True
      schema:
        type: "string"
    lname:
      name: "lname"
      description: "User's last name"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /users:
    get:
      operationId: "users.read_all"
      tags:
        - "Users"
      summary: "Read the list of users"
      responses:
        "200":
          description: "Successfully read the list of users"

    post:
      operationId: "users.create"
      tags:
        - Users
      summary: "Create a new user"
      requestBody:
        description: "User to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "user"
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: "Successfully created a new user"

  /users/lname:
    get:
      operationId: "users.read_one"
      tags:
        - Users
      summary: "Read one person"
      parameters:
        - $ref: "#/components/parameters/fname"
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully read user"

    put:
      tags:
        - Users
      operationId: "users.update"
      summary: "Update a user"
      parameters:
        - $ref: "#/components/parameters/fname"
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully updated user"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "user"
              $ref: "#/components/schemas/User"

    delete:
      tags:
        - Users
      operationId: "users.delete"
      summary: "Delete a user"
      parameters:
        - $ref: "#/components/parameters/fname"
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully deleted user"
