openapi: 3.0.0
info:
  title: "Grace API"
  description: "A REST API for Users to store and utilize database information."
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /churches:
    get:
      operationId: "churches.read_all"
      tags: -"Churches"
      summary: "Lists all churches at this location"
      responses:
        "200":
          description: "Successfully reads all available churches"
