openapi: 3.0.0
info:
  title: "Grace API"
  description: "A REST API for Users to store and utilize database information."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Church:
      type: "object"
      required:
        - name
        - phone

      properties:
        name:
          type: "string"
        phone:
          type: "string"
        address:
          type: "string"
        address2:
          type: "string"
        city:
          type: "string"
        state:
          type: "string"
        zip:
          type: "string"
        timestamp:
          type: "string"

  parameters:
    name:
      name: "name"
      description: "Name of the church to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /churches:
    get:
      operationId: "churches.read_all"
      tags:
        - "Churches"
      summary: "Lists all churches at this location"
      responses:
        "200":
          description: "Successfully reads all available churches"

    post:
      operationId: "churches.create"
      tags:
        - "Churches"
      summary: "Create a new church"
      requestBody:
        description: "Church to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "church"
              $ref: "#/components/schemas/Church"
      responses:
        "201":
          description: "Successfully created a new church"

  /churches/{name}:
    get:
      operationId: "churches.read_one"
      tags:
        - Church
      summary: "Read one church"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully read church"

    put:
      tags:
        - Church
      operationId: "churches.update"
      summary: "Update a church"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully updated church"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "church"
              $ref: "#/components/schemas/Church"

    delete:
      tags:
        - Church
      operationId: "churches.delete"
      summary: "Delete a church"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "204":
          description: "Successfully deleted {name}"
