openapi: 3.0.0
info:
  title: "Grace API"
  description: "A REST API for Users to store and utilize database information."
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /members:
    get:
      operationId: "members.read_all"
      tags:
        - "Members"
      summary: "Retrieve a list of members"
      responses:
        "200":
          description: "You have succefully retrieved a list of members"
