openapi: 3.0.0
info:
  title: "Grace API"
  description: "A REST API for Users to store and utilize database information."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Member:
      type: "object"
      required:
        - email
        - password
        - firstName
        - lastName
      properties:
        email:
          type: "string"
        password:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"

  parameters:
    lastName:
      name: "lastName"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /members:
    get:
      operationId: "members.read_all"
      tags:
        - "Members"
      summary: "Retrieve a list of members"
      responses:
        "200":
          description: "You have succefully retrieved a list of members"

    post:
      operationId: "members.create"
      tags:
        - "Member"
      summary: "Create a new member"
      requestBody:
        description: "Person to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "member"
              $ref: "#/components/schemas/Member"
      responses:
        "201":
          description: "Successfully created a new member"

  /members/{lastName}:
    get:
      operationId: "members.read_one"
      tags:
        - "Member"
      summary: "Read one member"
      parameters:
        - $ref: "#/components/parameters/lastName"
      responses:
        "200":
          description: "Successfully read the member information"

    put:
      tags:
        - "Member"
      operationId: "members.update"
      summary: "Update a member"
      parameters:
        - $ref: "#/components/parameters/lastName"
      responses:
        "200":
          description: "Successfully updated the member information"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "member"
              $ref: "#/components/schemas/Member"

    delete:
      tags:
        - "Member"
      operationId: "members.delete"
      summary: "Delete a member"
      parameters:
        - $ref: "#/components/parameters/lastName"
      responses:
        "204":
          description: "Successfully deleted them member"
